### ISSUE TITLE
增加自动解析坐标系功能

### ISSUE THREAD

**Issue by yangyanggu** [yangyanggu/layer-3dtiles#1]
当前插件只支持box，尝试增加对region的解析以及移除插件的position属性，直接解析tile.json中的经纬度

**Comment by Bana0** [comment]
自动解析坐标就是不需要设置position属性吗？

**Comment by yangyanggu** [comment]
> 自动解析坐标就是不需要设置position属性吗？

对，原本坐标就是存在于tile.json文件中，之前的解决方法舍弃了坐标，后续会研究加上直接读取坐标能力

**Comment by Bana0** [comment]
不设置position属性就会默认跟着地图的center属性显示

**Comment by yangyanggu** [comment]
不会，只是变更得到position的方式，原来是外部设置，修改为插件内直接读取文件

**Comment by Bana0** [comment]
![image](https://github.com/yangyanggu/layer-3dtiles/assets/112368598/8fbd7830-99ae-405e-afba-fae2dd5f18b1)
![image](https://github.com/yangyanggu/layer-3dtiles/assets/112368598/74c8b7fa-e301-4f9b-bd07-3c04b43a5d35)
这样设置出来就是跟着center属性显示的啊？

**Comment by yangyanggu** [comment]
> ![image](https://user-images.githubusercontent.com/112368598/252980447-8fbd7830-99ae-405e-afba-fae2dd5f18b1.png) ![image](https://user-images.githubusercontent.com/112368598/252980567-74c8b7fa-e301-4f9b-bd07-3c04b43a5d35.png) 这样设置出来就是跟着center属性显示的啊？

跟center没关系，内部有根据实际位置计算，最后实际生成的坐标系结果是投影坐标

**Comment by Bana0** [comment]
那假如我想把center的坐标设置成重庆，那模型的位置是显示到重庆还是模型自带经纬度的位置？

**Comment by yangyanggu** [comment]
显示自带的，你修改中心点，只是调整当前地图视图的位置，但地图上世界坐标的东西不会变

**Comment by Bana0** [comment]
![image](https://github.com/yangyanggu/layer-3dtiles/assets/112368598/31c86fbd-9f0a-4af2-b818-3cad385d7b7d)
![image](https://github.com/yangyanggu/layer-3dtiles/assets/112368598/1332da9f-fbbd-4537-839f-c6029e5a76be)
两个osgb的坐标哪一个转换出来的3dtiles文件的坐标更容易被读取？

**Comment by yangyanggu** [comment]
都一样，最后生成的都是投影坐标

**Comment by Bana0** [comment]
这个投影坐标是个什么意思？？

**Comment by yangyanggu** [comment]
> 这个投影坐标是个什么意思？？

只要保证你这边的坐标是你的模型的使用的就好了，模型生成都是球心坐标，我插件内部解析都会根据这个球心坐标解析出中心点的WGS84的坐标，再转化为高德的投影坐标上图。

**Comment by Bana0** [comment]
在3D地图上的模型上添加标记，如何才能让标记随着模型旋转而不飘逸？
